var aufgabenPool_1_2 = [
    { format: 'freitext', tabellenformat: 'quer', kopfzeile: ['', '1', '2', '3', '4', '5'], zeilen: [{ label: 'Anzahl Äpfel', werte: ['1', '2', '3', '4', '5'] }, { label: 'Preis in €', werte: ['0,50', '1,00', '1,50', '2,00', '2,50'] }], frage: 'Wie nennt man die Größe in der <strong>oberen Zeile</strong>?', richtig: ['ausgangsgröße', 'ausgangsgroesse', 'ausgangs größe'], erklaerung: 'Die obere Zeile zeigt die Anzahl der Äpfel – das ist die Ausgangsgröße.' },
    { format: 'freitext', tabellenformat: 'quer', kopfzeile: ['', '1', '2', '3', '4', '5'], zeilen: [{ label: 'Zeit in Minuten', werte: ['1', '2', '3', '4', '5'] }, { label: 'Füllmenge in Litern', werte: ['3', '6', '9', '12', '15'] }], frage: 'Wie nennt man die Größe in der <strong>unteren Zeile</strong>?', richtig: ['zugeordnete größe', 'zugeordnete groesse', 'zugeordnetegröße', 'zugeordnete grösse'], erklaerung: 'Die untere Zeile zeigt die Füllmenge – das ist die zugeordnete Größe.' },
    { format: 'freitext', tabellenformat: 'hoch', spalten: ['Anzahl Kekse', 'Einnahmen in €'], zeilen: [['5','2,50'],['10','5,00'],['15','7,50'],['20','10,00']], frage: 'Wie nennt man die Größe in der <strong>linken Spalte</strong>?', richtig: ['ausgangsgröße', 'ausgangsgroesse', 'ausgangs größe'], erklaerung: 'Die linke Spalte zeigt die Anzahl der Kekse – das ist die Ausgangsgröße.' },
    { format: 'freitext', tabellenformat: 'hoch', spalten: ['Mietdauer (Tage)', 'Kosten (€)'], zeilen: [['1','8'],['3','24'],['5','40'],['7','56']], frage: 'Wie nennt man die Größe in der <strong>rechten Spalte</strong>?', richtig: ['zugeordnete größe', 'zugeordnete groesse', 'zugeordnetegröße', 'zugeordnete grösse'], erklaerung: 'Die rechte Spalte zeigt die Kosten – das ist die zugeordnete Größe.' },
    { format: 'freitext', tabellenformat: null, situation: 'Ein Taxifahrer fährt unterschiedlich viele Kilometer. Je mehr Kilometer der Fahrgast fährt, desto mehr zahlt er.', frage: 'Wie nennt man die Kilometerzahl in dieser Zuordnung?', richtig: ['ausgangsgröße', 'ausgangsgroesse', 'ausgangs größe'], erklaerung: 'Die Kilometerzahl ist die Ausgangsgröße – sie wird vorgegeben und der Preis ergibt sich daraus.' },
    { format: 'freitext', tabellenformat: null, situation: 'In einer Bäckerei hängt die Anzahl der Brötchen davon ab, wie viel Mehl verwendet wird.', frage: 'Wie nennt man die Anzahl der Brötchen in dieser Zuordnung?', richtig: ['zugeordnete größe', 'zugeordnete groesse', 'zugeordnetegröße', 'zugeordnete grösse'], erklaerung: 'Die Anzahl der Brötchen ist die zugeordnete Größe – sie ergibt sich aus der Mehlmenge.' },
    { format: 'freitext', tabellenformat: null, situation: 'Diese Größe wird vorgegeben. Von ihr hängt die andere Größe ab.', frage: 'Wie nennt man diese Größe?', richtig: ['ausgangsgröße', 'ausgangsgroesse', 'ausgangs größe'], erklaerung: 'Das ist die Ausgangsgröße – sie wird vorgegeben und bestimmt den Wert der anderen Größe.' },
    { format: 'freitext', tabellenformat: null, situation: 'Diese Größe ergibt sich aus der anderen. Sie wird nicht vorgegeben, sondern berechnet oder abgelesen.', frage: 'Wie nennt man diese Größe?', richtig: ['zugeordnete größe', 'zugeordnete groesse', 'zugeordnetegröße', 'zugeordnete grösse'], erklaerung: 'Das ist die zugeordnete Größe – sie ergibt sich aus der Ausgangsgröße.' },
    { format: 'mc_erklaerung', kontext: 'Max sagt: „Die Ausgangsgröße ist immer die kleinere Zahl."', frage: 'Hat Max recht?', optionen: ['Ja, die Ausgangsgröße ist immer kleiner.', 'Nein, die Ausgangsgröße ist die Größe, die vorgegeben wird – sie kann auch größer sein.', 'Nein, die Ausgangsgröße ist immer die größere Zahl.', 'Ja, weil x immer kleiner als y ist.'], richtig: 1, erklaerung: 'Die Ausgangsgröße ist die Größe, von der die Zuordnung ausgeht – sie kann größer oder kleiner sein.' },
    { format: 'mc_erklaerung', kontext: 'Lisa sagt: „Beim Taxifahren ist der Preis die Ausgangsgröße, weil ich den Preis bezahle."', frage: 'Hat Lisa recht?', optionen: ['Ja, weil der Preis am Ende steht.', 'Nein, die Kilometeranzahl ist die Ausgangsgröße – der Preis ergibt sich daraus.', 'Ja, weil der Preis vorgegeben ist.', 'Nein, weil Geld keine Größe ist.'], richtig: 1, erklaerung: 'Die Ausgangsgröße ist die Kilometerzahl – sie wird vorgegeben. Der Preis ist die zugeordnete Größe.' },
    { format: 'mc_erklaerung', kontext: 'Wertetabelle: x = Mehl in g, y = Anzahl Brötchen. Tim sagt: „x ist die zugeordnete Größe, weil y von x abhängt."', frage: 'Hat Tim recht?', optionen: ['Ja, weil y von x abhängt.', 'Nein, wenn y von x abhängt, ist x die Ausgangsgröße – nicht die zugeordnete.', 'Ja, die zugeordnete Größe steht immer links.', 'Nein, weil x immer die Ausgangsgröße ist.'], richtig: 1, erklaerung: 'Wenn y von x abhängt, ist x die Ausgangsgröße. Die zugeordnete Größe ist y.' },
    { format: 'mc_erklaerung', kontext: 'Anna sagt: „Die zugeordnete Größe wird berechnet oder abgelesen – sie hängt von der Ausgangsgröße ab."', frage: 'Hat Anna recht?', optionen: ['Nein, die zugeordnete Größe wird vorgegeben.', 'Nein, beide Größen werden berechnet.', 'Ja, das ist eine korrekte Erklärung.', 'Ja, aber nur wenn x kleiner als y ist.'], richtig: 2, erklaerung: 'Anna hat recht – die zugeordnete Größe ergibt sich aus der Ausgangsgröße.' }
  ];
